repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13  # Specify the version of Ruff
    hooks:
      - id: ruff-check  # Run the linter
        args: [ --fix ]
      - id: ruff-format  # Run the formatter

    