"""test

Revision ID: 319cea50b8fd
Revises: 
Create Date: 2025-07-26 10:03:05.015844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319cea50b8fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('food_required', sa.Integer(), nullable=False))
    op.add_column('seasons', sa.Column('herb_attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'herb_attempts')
    op.drop_column('roles', 'food_required')
    # ### end Alembic commands ###
