"""empty message

Revision ID: 974d171120dc
Revises: f4a010096847
Create Date: 2025-09-18 11:22:29.998211

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "974d171120dc"
down_revision: Union[str, Sequence[str], None] = "f4a010096847"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("clans", "is_true_clan", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_constraint(None, "clans", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "clans", "characters", ["leader"], ["no"])
    op.alter_column("clans", "is_true_clan", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
